config/routes.rb
Rails.application.routes.draw do
  resources :directors
  scope module: :api do
    resources :movies
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/director.rb
class Director < ApplicationRecord
    has_many :movies
    validates :first_name, presence: true
    validates :last_name, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
    belongs_to :director
    validates :name, presence: true
    validates :publication_year, presence: true, length: {maximum: 4}, comparison: { less_than: 2023 }
end

app/models/movie_director.rb
class MovieDirector < ApplicationRecord
  has_many :movies
  validates :name, presence: true
  validates :lastname, presence: true
end

app/controllers/api/movies_controller.rb
module Api
class MoviesController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_movie, only: %i[ show edit update destroy ]
  before_action :set_directors

  def index
    @movies = Movie.all
  end

  def show; end

  def new
    @movie = Movie.new
  end

  def edit; end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      render 'api/movies/show', status: :created
    else
      render json: @movie.errors, status: :unprocessable_entity 
    end
  end

  def update
    if @movie.update(movie_params)
      render 'api/movies/show', status: :created
    else
      render json: @movie.errors, status: :unprocessable_entity 
    end
  end

  def destroy
    @movie.destroy

    render 'api/movies/show', status: :created
  end

  private
    def set_movie
      @movie = Movie.find(params[:id])
    end

    def set_directors
      @directors = Director.all.map {|director| ["#{director.first_name} #{director.last_name}"  ,director.id] }
    end

    def movie_params
      params.require(:movie).permit(:name, :publication_year, :director_id)
    end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  before_action :set_director, only: %i[ show edit update destroy ]

  def index
    @directors = Director.all
  end

  def show
  end

  def new
    @director = Director.new
  end

  def edit
  end

  def create
    @director = Director.new(director_params)

    respond_to do |format|
      if @director.save
        format.html { redirect_to director_url(@director), notice: "Director was successfully created." }
        format.json { render :show, status: :created, location: @director }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @director.update(director_params)
        format.html { redirect_to director_url(@director), notice: "Director was successfully updated." }
        format.json { render :show, status: :ok, location: @director }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @director.destroy

    respond_to do |format|
      format.html { redirect_to directors_url, notice: "Director was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_director
      @director = Director.find(params[:id])
    end

    def director_params
      params.require(:director).permit(:first_name, :last_name)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]

  # GET /movies or /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1 or /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:name, :year)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/helpers/movie_directors_helper.rb
module MovieDirectorsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/directors/_director.html.erb
<div id="<%= dom_id director %>">
  <p>
    <strong>First name:</strong>
    <%= director.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= director.last_name %>
  </p>

</div>

app/views/directors/_director.html.haml
%div{:id => "#{dom_id director}"}
  %p
    %strong Name:
    = director.first_name

   %p
    %strong Last name:
    = director.last_name

app/views/directors/_form.html.erb
<%= form_with(model: director) do |form| %>
  <% if director.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(director.errors.count, "error") %> prohibited this director from being saved:</h2>

      <ul>
        <% director.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/directors/_form.html.haml
= form_for @director, validate: true do |f|
  .form-group.ml-4.mr-4
    = f.label :first_name, class: "form-label required"
    = f.text_field :first_name, autofocus: true, class: "form-control"

    .form-group.ml-4.mr-4
    = f.label :last_name, class: "form-label required"
    = f.text_field :last_name, autofocus: true, class: "form-control"

  .row
    .offset-3.col-3
      = link_to t('application.back_to', model: t('activerecord.modules.director.other')), directors_path, class: "btn btn-secondary btn-block"
      
    .col-3
      = button_tag t('application.save', model: t('activerecord.modules.director.one')), class: "btn btn-outline-success btn-block", 
          'data-disable-with': "Guardando..."

app/views/directors/edit.html.erb
<h1>Editing director</h1>

<%= render "form", director: @director %>

<br>

<div>
  <%= link_to "Show this director", @director %> |
  <%= link_to "Back to directors", directors_path %>
</div>

app/views/directors/edit.html.haml
.page_header
  %h1.mb-4
    = t('application.new', model: t('activerecord.modules.director.one'))
= render "form"

app/views/directors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Directors</h1>

<div id="directors">
  <% @directors.each do |director| %>
    <%= render director %>
    <p>
      <%= link_to "Show this director", director %>
    </p>
  <% end %>
</div>

<%= link_to "New director", new_director_path %>

app/views/directors/index.html.haml
.page.header
  %p{:style => "color: green"}= notice
  %h1.mb-4
    = t('application.list_of', model: t('activerecord.modules.director.other'))
    .float-right
      = link_to t('application.new', model: t('activerecord.modules.director.one')), new_director_path, class: "btn btn-primary"
  
  %table.table.table-striped
    %thread
      %tr
        %th= t('activerecord.attributes.director.first_name')
        %th= t('activerecord.attributes.director.last_name')
        %th
        %th
    %tbody
      - @directors.each do |director|
        %tr
          %td= director.first_name
          %td= director.last_name
          %td= link_to t('application.show', model: t('activerecord.modules.director.one')), director, class: "btn btn-info"
          %td= link_to t('application.edit', model: t('activerecord.modules.director.one')), edit_director_path(director), class: "btn btn-success"
          %td= link_to t('application.remove', model: t('activerecord.modules.director.one')), director, method: :delete, class: "btn btn-danger",
                                data: {confirm: "¿Desea eliminarlo?",
                                accept: "OK",
                                reject: "Cancelar"}

app/views/directors/new.html.erb
<h1>New director</h1>

<%= render "form", director: @director %>

<br>

<div>
  <%= link_to "Back to directors", directors_path %>
</div>

app/views/directors/new.html.haml
.page_header
  %h1.mb-4
    = t('application.new', model: t('activerecord.modules.director.one'))
= render "form"

app/views/directors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @director %>

<div>
  <%= link_to "Edit this director", edit_director_path(@director) %> |
  <%= link_to "Back to directors", directors_path %>

  <%= button_to "Destroy this director", @director, method: :delete %>
</div>

app/views/directors/show.html.haml
%p#notice= notice

.card
  .card-body
    %h5.card-title Nombre:
    %p.card-text &nbsp #{@director.first_name}

    .card-body
    %h5.card-title Apellido:
    %p.card-text &nbsp #{@director.last_name}

.row.mt-3
  .offset-3.col-3
    = link_to t('application.back_to', model: t('activerecord.modules.director.other')), directors_path, class: "btn btn_secondary btn block"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Lenguajes1
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    = yield

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |form| %>
  <% if movie.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :year, style: "display: block" %>
    <%= form.number_field :year %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/_form.html.haml
= form_for @movie, validate: true do |f|
  .form-group.ml-4.mr-4
    = f.label :name, class: "form-label required"
    = f.text_field :name, autofocus: true, class: "form-control"

  .form-group.ml-4.mr-4
    = f.label :year, class: "form-label required"
    = f.text_field :year, autofocus: true, class: "form-control"

  .form-group.ml-4.mr-4
    = f.label :director_id, class: "form-label required"
    = f.select(:director_id, options_for_select(@directors, @movie.director),
                        {prompt:"Seleccione"}, class: "form-control")

  .row
    .offset-3.col-3
      = link_to t('application.back_to', model: t('activerecord.modules.movie.other')), movies_path, class: "btn btn-secondary btn-block"
      
    .col-3
      = button_tag t('application.save', model: t('activerecord.modules.movie.one')), class: "btn btn-outline-success btn-block", 
          'data-disable-with': "Guardando..."

app/views/movies/_movie.html.erb
<div id="<%= dom_id movie %>">
  <p>
    <strong>Name:</strong>
    <%= movie.name %>
  </p>

  <p>
    <strong>Year:</strong>
    <%= movie.year %>
  </p>

</div>

app/views/movies/_movie.html.haml
%div{:id => "#{dom_id movie}"}
  %p
    %strong Name:
    = movie.name

   %p
    %strong Year:
    = movie.Year

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Show this movie", @movie %> |
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/edit.html.haml
.page_header
  %h1.mb-4
    = t('application.new', model: t('activerecord.modules.movie.one'))
= render "form"

app/views/movies/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Movies</h1>

<div id="movies">
  <% @movies.each do |movie| %>
    <%= render movie %>
    <p>
      <%= link_to "Show this movie", movie %>
    </p>
  <% end %>
</div>

<%= link_to "New movie", new_movie_path %>

app/views/movies/index.html.haml
.page.header
  %p{:style => "color: green"}= notice
  %h1.mb-4
    = t('application.list_of', model: t('activerecord.modules.movie.other'))
    .float-right
      = link_to t('application.new', model: t('activerecord.modules.movie.one')), new_movie_path, class: "btn btn-primary"
  
  %table.table.table-striped
    %thread
      %tr
        %th= t('activerecord.attributes.movie.name')
        %th= t('activerecord.attributes.movie.year')
        %th= t('activerecord.attributes.movie.director.Director')
        %th
        %th
    %tbody
      - @movies.each do |movie|
        %tr
          %td= movie.name
          %td= movie.year
          %td= movie.director.first_name
          %td= link_to t('application.show', model: t('activerecord.modules.movie.one')), movie, class: "btn btn-info"
          %td= link_to t('application.edit', model: t('activerecord.modules.movie.one')), edit_movie_path(movie), class: "btn btn-success"
          %td= link_to t('application.remove', model: t('activerecord.modules.movie.one')), movie, method: :delete, class: "btn btn-danger",
                                data: {confirm: "¿Desea eliminarlo?",
                                accept: "OK",
                                reject: "Cancelar"}

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/new.html.haml
.page_header
  %h1.mb-4
    = t('application.new', model: t('activerecord.modules.movie.one'))
= render "form"

app/views/movies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @movie %>

<div>
  <%= link_to "Edit this movie", edit_movie_path(@movie) %> |
  <%= link_to "Back to movies", movies_path %>

  <%= button_to "Destroy this movie", @movie, method: :delete %>
</div>

app/views/movies/show.html.haml
%p#notice= notice

.card
  .card-body
    %h5.card-title Nombre:
    %p.card-text &nbsp #{@movie.name}

    .card-body
    %h5.card-title Año:
    %p.card-text &nbsp #{@movie.year}

.row.mt-3
  .offset-3.col-3
    = link_to t('application.back_to', model: t('activerecord.modules.movie.other')), movies_path, class: "btn btn_secondary btn block"